name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            if ! command -v libreoffice &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y libreoffice
            fi
            cd /var/www/nsg-be
            git reset --hard
            git pull origin main
            pm2 restart all || pm2 restart nsg-be
            pm2 save
      - name: Deploy to VPS 160.25.166.176 via SSH
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: 160.25.166.176
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            if [ -d "/var/www/nsg-be" ]; then
              cd /var/www/nsg-be
            elif [ -d "/var/www/NSG_DocumentMange_BE" ]; then
              cd /var/www/NSG_DocumentMange_BE
            fi
            pwd
            git reset --hard
            git pull origin main
            pm2 restart all
            pm2 save


